name: Generate API docs and publish to Github Pages

env:
  BRANCHLIST: "MDL-81407-main"
  VERSIONLIST: "main"

on:
  schedule:
    # Publish every Sunday at 1:30am
    - cron: '30 1 * *  0'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          show-progress: ''

      - name: Checkout Moodle
        uses: actions/checkout@v4
        with:
          repository: andrewnicols/moodle
          path: .moodle
          show-progress: ''
          branches: ${{ env.BRANCHLIST }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.moodle/.nvmrc'

      - name: Run ignorefiles
        run:
          cd .moodle
          npm install
          npx grunt ignorefiles

      - name: Run phpdoc
        run: |
          docker run --rm -v $(pwd)/.moodle:/data phpdoc/phpdoc:3 -c phpdoc.xml

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./phpdocs/api
          cname: andrewnicols.github.io
